#define NUMBER_OF_STANDS 3
#define NUMBER_OF_TICKET_OFFICES 1
#define NUMBER_OF_REPLENISHMENT 1
#define NUMBER_OF_CLIENTS 100
#define NUMBER_OF_SEATS 255

#define PRIORITY_FACTOR 3

#define TICKET_PRICE 6.9
#define POPCORN_PRICE 5
#define DRINK_PRICE 2

#define MAX_POPCORN_AMOUNT 30
#define MAX_DRINKS_AMOUNT 30

